os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.11.2"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=8.11.2
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
install:
script:
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
